version: '3'

services:
  db:
    image: 'postgres:12-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: 'redis:5-alpine'
    command: redis-server
    ports:
      - '6386:6379'
    volumes:
      - 'redis:/data'

  web:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3007:3000'
    environment:
      - DATABASE_HOST=db

volumes:
  redis:
  postgres: